name: Build frontend snapshot

on:
  workflow_dispatch:
     
jobs:
  build:
    runs-on: windows-2025
    env:
      SOLUTION_NAME: MDD4All.DME.sln
      STARTUP_PROJECT: MDD4All.DME.App.Wpf\src\MDD4All.DME.App.Wpf\MDD4All.DME.App.Wpf-dev.csproj
      OUTPUT_PATH: .\output\Synorvia\
      
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Set version number from date using PS
      uses: Amadevus/pwsh-script@v2
      id: date-version
      with:
        script: |
            ([datetime]::now).tostring("yyyy.M.d")

    - name: Set version variable from date and build number
      env: 
        DATE_VERSION: ${{steps.date-version.outputs.result}}
      run: echo ("VERSION=" + $env:DATE_VERSION + "." + $env:GITHUB_RUN_NUMBER) >> $env:GITHUB_ENV

    - name: Echo version number
      run: echo $env:VERSION

    - name: Publish
      run: dotnet publish -p:PublishProfile=FolderProfile -r Win-86 -c Release /p:Version=${{env.VERSION}} .\src\${{env.STARTUP_PROJECT}}

    - name: Create output directories
      run: |
        mkdir output
        mkdir ${{env.OUTPUT_PATH}}
        mkdir artifacts

    - name: Copy Synorvia app files
      run: |
        robocopy /E .\src\MDD4All.DME\bin\Release\net9.0-windows7.0\publish\win-x86\ ${{env.OUTPUT_PATH}}
        if ($lastexitcode -lt 8) { exit 0 } else { exit 1 }

    - name: Zip Synorvia files
      uses: thedoctor0/zip-release@0.7.1
      with:
        directory: output\Synorvia\
        filename: Synorvia_${{env.VERSION}}.zip

    - name: Copy Synorvia zip file to dist directory
      run: xcopy /y .\output\Synorvia\Synorvia_${{env.VERSION}}.zip .\artifacts\

    - name: Upload SpecIFicator artifact
      uses: actions/upload-artifact@v4
      with:
        name: Synorvia_${{env.VERSION}}
        path: artifacts\*.zip